image: docker:latest
services:
 - docker:dind

before_script:
    - docker login -u CI_USER -p $CI_USER_TOKEN scm.cms.hu-berlin.de:4567

variables:
    # https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    RELEASE_IMAGE: scm.cms.hu-berlin.de:4567/berlinunited/tools/linuxtoolchain

create_toolchain:
  script:
    - docker build -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE
