stages:
  - build
  - deploy
  - test

image: docker:latest
services:
 - docker:dind

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN scm.cms.hu-berlin.de:4567
    # - docker login -u CI_USER -p $CI_USER_TOKEN scm.cms.hu-berlin.de:4567

variables:
    # https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    RELEASE_IMAGE: scm.cms.hu-berlin.de:4567/berlinunited/tools/linuxtoolchain
    TOOLCHAIN_TRIGGER: abc

build_toolchain:
  stage: build
  except:
    refs:
      - master
  script:
    - echo "only build the toolchain"
    - docker build -t $RELEASE_IMAGE .

# TODO how to do manual deployment?
.build_and_deploy_toolchain:
  stage: deploy
  only:
    refs:
      - master
      - web
  script:
    - echo "build and deploy the toolchain"
    - docker build -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE

build_naoth:
  stage: test
  only:
    refs:
      - master
      - web
  trigger:
    project: https://scm.cms.hu-berlin.de/berlinunited/naoth-2020
    branch: infrastructure/improve_ci
    strategy: depend  # does not seem to work yet