# Base OS layer: Latest Ubuntu LTS.
FROM ubuntu:18.04

# Install system dependencies
RUN apt-get update -y --fix-missing \
    && apt-get --no-install-recommends install build-essential \
    cmake zlib1g-dev git libreadline-dev gettext cppcheck python-pip -y \
    && pip install pygments \
    && rm -rf /var/lib/apt/lists/*